### ISSUE TITLE
How can I access the code files of this book?

### ISSUE THREAD

**Issue by rpalsaxena** [bpbpublications/Elements-of-Deep-Learning-for-Computer-Vision#1]
HI,
I am reading this book but I am facing issues while debugging code. Can you please push the files in repo?

**Comment by bpbpublications** [comment]
Hi Rahul, 

We have pushed the code files in the repository, hope your issue is resolved now.

**Comment by rpalsaxena** [comment]
Thanks!
It looks good to me :)
